### ISSUE TITLE
Angular 5 Universal server render problem

### ISSUE THREAD

**Issue by necipsunmaz** [ihym/ngx-card#11]
PS C:\my-path\angular-universal> node dist/server.js
C:\my-path\angular-universal\node_modules\ngx-card\card.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, Input, ContentChildren, ElementRef } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\my-path\angular-universal\dist\server.js:1:1302699)

I am trying to run Server.js, but card.js gives me this error.
How can I fix this problem?

document: https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c

**Comment by MehmetSert** [comment]
> PS C:\my-path\angular-universal> node dist/server.js
> C:\my-path\angular-universal\node_modules\ngx-card\card.js:1
> (function (exports, require, module, __filename, __dirname) { import { Directive, Input, ContentChildren, ElementRef } from '@angular/core';
> ^^^^^^
> 
> SyntaxError: Unexpected token import
> at createScript (vm.js:80:10)
> at Object.runInThisContext (vm.js:139:10)
> at Module._compile (module.js:607:28)
> at Object.Module._extensions..js (module.js:654:10)
> at Module.load (module.js:556:32)
> at tryModuleLoad (module.js:499:12)
> at Function.Module._load (module.js:491:3)
> at Module.require (module.js:587:17)
> at require (internal/module.js:11:18)
> at Object. (C:\my-path\angular-universal\dist\server.js:1:1302699)
> 
> I am trying to run Server.js, but card.js gives me this error.
> How can I fix this problem?
> 
> document: https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c

I have the same problem. Did you find the solution?

**Comment by necipsunmaz** [comment]
> > PS C:\my-path\angular-universal> node dist/server.js
> > C:\my-path\angular-universal\node_modules\ngx-card\card.js:1
> > (function (exports, require, module, __filename, __dirname) { import { Directive, Input, ContentChildren, ElementRef } from '@angular/core';
> > ^^^^^^
> > SyntaxError: Unexpected token import
> > at createScript (vm.js:80:10)
> > at Object.runInThisContext (vm.js:139:10)
> > at Module._compile (module.js:607:28)
> > at Object.Module._extensions..js (module.js:654:10)
> > at Module.load (module.js:556:32)
> > at tryModuleLoad (module.js:499:12)
> > at Function.Module._load (module.js:491:3)
> > at Module.require (module.js:587:17)
> > at require (internal/module.js:11:18)
> > at Object. (C:\my-path\angular-universal\dist\server.js:1:1302699)
> > I am trying to run Server.js, but card.js gives me this error.
> > How can I fix this problem?
> > document: https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c
> 
> I have the same problem. Did you find the solution?

No, but i solved this problem with [Google Chrome Rendertron](https://github.com/GoogleChrome/rendertron). I advise.

**Comment by MehmetSert** [comment]
Thank you. I will examine.
